# Copyright 2025 Jeff Hodsdon
# SPDX-License-Identifier: Apache-2.0

"""Generation of the temporary apple_static_xcframework BUILD package.

For large, ObjC/C-heavy modules, recompiling every Pod/SPM dependency from
source through SwiftPM is brittle (Bazel-relative #import paths, module maps,
mixed-language targets, etc. cannot be faithfully reproduced). Instead we build
each ObjC/C Pod/SPM dependency into a static xcframework via rules_apple's
`apple_static_xcframework` and consume it as a SwiftPM `.binaryTarget`.

This module produces the BUILD.bazel content for that temporary package. Each
module is emitted as:

    apple_static_xcframework(
        name = "<Module>",
        bundle_name = "<Module>",
        deps = ["<exact objc/cc library target>"],
        public_hdrs = [<module's public headers>],
        avoid_deps = [<module's direct library deps>],  # only its own code is bundled
        minimum_os_versions = {"ios": "<min>"},
        ios = {"simulator": [...], "device": [...]},
    )

`avoid_deps` is essential: without it each xcframework would statically embed
its transitive deps, producing duplicate symbols when many xcframeworks are
linked into one preview binary.
"""

# rules_apple internal swiftpkg/Pods targets are package-private, so the build
# of this generated package must be run with --nocheck_visibility.
GENERATED_BUILD_HEADER = """# GENERATED by rules_swift_previews - DO NOT EDIT.
# Regenerate with: bazel run <target>_gen
#
# Temporary package that builds ObjC/C Pod & SPM dependencies as static
# xcframeworks for SwiftUI previews. Build with:
#   bazel build --nocheck_visibility //{package}:all
"""

def _format_str_list(labels, indent):
    if not labels:
        return "[]"
    pad = " " * indent
    inner = " " * (indent + 4)
    lines = ["["]
    for label in labels:
        lines.append('{inner}"{label}",'.format(inner = inner, label = label))
    lines.append(pad + "]")
    return "\n".join(lines)

def _format_arch_dict(variant_to_archs, indent):
    pad = " " * indent
    inner = " " * (indent + 4)
    lines = ["{"]
    for variant, archs in variant_to_archs.items():
        archs_str = ", ".join(['"{}"'.format(a) for a in archs])
        lines.append('{inner}"{variant}": [{archs}],'.format(
            inner = inner,
            variant = variant,
            archs = archs_str,
        ))
    lines.append(pad + "}")
    return "\n".join(lines)

def generate_xcframework_target(
        module_name,
        target_label,
        public_hdrs,
        avoid_deps,
        ios_version,
        ios_variants):
    """Generate a single apple_static_xcframework target block.

    Args:
        module_name: The module / bundle name (e.g. "FirebaseCore").
        target_label: Exact objc/cc library label to wrap.
        public_hdrs: List of public header label strings.
        avoid_deps: List of direct dependency label strings to exclude.
        ios_version: Minimum iOS version string (e.g. "15.0").
        ios_variants: dict mapping platform variant ("simulator"/"device") to arch lists.

    Returns:
        A string containing the target declaration.
    """

    # Framework module identifiers must be valid C identifiers: hyphens and dots
    # (e.g. "GoogleUtilities-Environment", "GoogleDataTransport.rspm_c") are not
    # allowed, so sanitize them for bundle_name. The Bazel target name keeps the
    # original (Bazel allows hyphens/dots) so it matches the SwiftPM target name.
    bundle_name = module_name.replace("-", "_").replace(".", "_")

    lines = [
        "apple_static_xcframework(",
        '    name = "{}",'.format(module_name),
        '    bundle_name = "{}",'.format(bundle_name),
        "    deps = [{}],".format('"{}"'.format(target_label)),
        "    public_hdrs = {},".format(_format_str_list(public_hdrs, 4)),
        "    avoid_deps = {},".format(_format_str_list(avoid_deps, 4)),
        '    minimum_os_versions = {{"ios": "{}"}},'.format(ios_version),
        "    ios = {},".format(_format_arch_dict(ios_variants, 4)),
        ")",
    ]
    return "\n".join(lines)

def generate_xcframework_build_content(
        package_name,
        binary_modules,
        ios_version = "15.0",
        ios_variants = None,
        load_statement = '''load("@build_bazel_rules_apple//apple:apple.bzl", "apple_static_xcframework")'''):
    """Generate the full BUILD.bazel content for the xcframework package.

    Args:
        package_name: The package path (for the header comment).
        binary_modules: dict mapping module_name -> {"target","hdrs","avoid_deps"}.
        ios_version: Minimum iOS version.
        ios_variants: dict variant->archs; defaults to simulator+device arm64.
        load_statement: The load statement for apple_static_xcframework.

    Returns:
        String content of the generated BUILD.bazel.
    """
    if ios_variants == None:
        ios_variants = {"simulator": ["arm64"], "device": ["arm64"]}

    lines = [
        GENERATED_BUILD_HEADER.format(package = package_name),
        load_statement,
        "",
    ]

    # Deterministic ordering for reproducible output.
    for module_name in sorted(binary_modules.keys()):
        meta = binary_modules[module_name]
        lines.append(generate_xcframework_target(
            module_name = module_name,
            target_label = meta["target"],
            public_hdrs = meta.get("hdrs", []),
            avoid_deps = meta.get("avoid_deps", []),
            ios_version = ios_version,
            ios_variants = ios_variants,
        ))
        lines.append("")

    return "\n".join(lines)
